# **Curso** : Python para Data Science

**Sesión 02.1**
Programación con Numpy y Pandas

**Profesor**:
* Ing. Cristhian Castro Chávez
* castro.ca@pucp.pe

In [1]:
# El primer paso es importar numpy y colocar un alias. Usaremos np
import numpy as np

### Ventajas de Usar Numpy

Primero comprobaremos que al usar Numpy estamos acortando los tiempos de ejecución y haciendo más eficiente el uso de los recursos

In [2]:
import time
# Crear una lista de Python con un millón de elementos
lista_python = list(range(10000000))

# Crear un arreglo de NumPy con los mismos elementos
arreglo_numpy = np.array(lista_python)

# Medir el tiempo de ejecución para sumar todos los elementos en la lista de Python
inicio = time.time()
suma_lista = sum(lista_python)
tiempo_lista = time.time() - inicio

# Medir el tiempo de ejecución para sumar todos los elementos en el arreglo de NumPy
inicio = time.time()
suma_numpy = np.sum(arreglo_numpy)
tiempo_numpy = time.time() - inicio

print("Tiempo de ejecución para lista de Python:", tiempo_lista)
print("Tiempo de ejecución para arreglo de NumPy:", tiempo_numpy)
print("Tiempo de ejecución de la lista es {:.2f} veces más usando listas".format(tiempo_lista/tiempo_numpy))

Tiempo de ejecución para lista de Python: 0.3796532154083252
Tiempo de ejecución para arreglo de NumPy: 0.0019941329956054688
Tiempo de ejecución de la lista es 190.39 veces más usando listas


* **Vectorización**
  * Vamos a crear 2 listas, cada una de 10,000 elementos y luego sumar elemento a elemento. Veremos que Numpy es mucho más eficiente.

In [3]:
# Crear dos arreglos NumPy
a = np.array(range(10000))
b = np.array(range(10000, 20000))

# Medir el tiempo de inicio
inicio = time.time()

# Realizar la suma de vectores usando vectorización
resultado = a + b

# Medir el tiempo de finalización
fin = time.time()

print("Tiempo de ejecución con NumPy: {:.6f} segundos".format(fin - inicio))

Tiempo de ejecución con NumPy: 0.000000 segundos


In [4]:
# Crear dos listas de Python
a = list(range(10000))
b = list(range(10000, 20000))

# Medir el tiempo de inicio
inicio = time.time()

# Inicializar una lista vacía para el resultado
resultado = []

# Realizar la suma de listas sin NumPy utilizando bucles for
for i in range(len(a)):
    suma = a[i] + b[i]
    resultado.append(suma)

# Medir el tiempo de finalización
fin = time.time()

print("Tiempo de ejecución sin NumPy: {:.6f} segundos".format(fin - inicio))

Tiempo de ejecución sin NumPy: 0.009010 segundos


In [5]:
0.001412/0.000092

15.347826086956522

In [6]:
# Ejemplo de Broadcasting
import numpy as np
import time

# Crear un vector NumPy
vector = np.array([1, 2, 3])

# Crear una matriz NumPy
matriz = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# Medir el tiempo de inicio
inicio = time.time()

# Realizar la operación de suma con broadcasting
resultado = vector + matriz

# Medir el tiempo de finalización
fin = time.time()

print("Resultado de la operación con broadcasting en NumPy:")
print(resultado)



Resultado de la operación con broadcasting en NumPy:
[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [7]:
# Crear un vector como una lista de Python
vector = [1, 2, 3]

# Crear una matriz como una lista de listas en Python
matriz = [[10, 20, 30],
          [40, 50, 60],
          [70, 80, 90]]

# Inicializar una lista vacía para el resultado
resultado = []

# Realizar la operación de suma sin broadcasting
for i in range(len(matriz)):
    fila_resultado = []
    for j in range(len(matriz[i])):
        suma = vector[j] + matriz[i][j]
        fila_resultado.append(suma)
    resultado.append(fila_resultado)

print("Resultado de la operación sin broadcasting (sin NumPy):")
for fila in resultado:
    print(fila)



Resultado de la operación sin broadcasting (sin NumPy):
[11, 22, 33]
[41, 52, 63]
[71, 82, 93]


### 2.1 NumPy Arrays y matrices

**NumPy Array**
* Un arreglo es una estructura de datos que almacena valores del mismo tipo de datos.
* Mientras que las listas en Python pueden contener valores correspondientes a diferentes tipos de datos, los arreglos en Python solo pueden contener valores del mismo tipo de datos.
* Sin embargo, las listas de Python no logran ofrecer el rendimiento necesario al realizar cálculos con conjuntos de datos numéricos grandes. Para resolver este problema, utilizamos arreglos de NumPy.
* Podemos crear arreglos de NumPy convirtiendo una lista en un arreglo.


In [8]:
# Definimos una lista de strings y una lista de números
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

arr_num = [5, 4, 6, 7, 3]

In [9]:
# Ahora convertimos cada una de las listas a un arregle de Numpy
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

# Verificamos las salidas
print('Numpy Array (arr_str): ',np_arr_str)
print('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num):  [5 4 6 7 3]


Los resultados se ven similares a una lista, pero arr_str y arr_num se han convertido en arreglos de NumPy. Verifiquemos el tipo de datos para confirmarlo.

In [10]:
# Imprimiendo el tipo de datos de las listas
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num))

# Imprimiendo el tipo de datos de los arreglos numpy
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


In [11]:
# Algunas funciones básicas de arreglos
np_arr_str

array(['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla'], dtype='<U8')

In [12]:
len(np_arr_str)

5

In [13]:
np_arr_str.shape

(5,)

**NumPy Matrix**

* Una matriz es una estructura de datos bidimensional en la que los elementos se organizan en filas y columnas.
* Una matriz se puede crear utilizando una lista de listas.

In [14]:
# Digamos que tenemos información sobre diferentes números de cilindros en varios coches y queremos mostrarlos en un formato de matriz. 
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [15]:
print('Tipo de Dato de la matriz: ',type(matrix))

Tipo de Dato de la matriz:  <class 'numpy.ndarray'>


* Observamos que todos los objetos de NumPy tienen el tipo de dato "ndarray".

### 2.2 NumPy Functions

**Hay diferentes formas de crear arreglos de NumPy utilizando las funciones disponibles en la biblioteca NumPy.**

**Usando np.arange() function**
* La función np.arange() devuelve un arreglo con elementos espaciados de manera uniforme según el intervalo. El intervalo mencionado es semiacotado, es decir, el inicio está incluido, pero el final está excluido.
* Tiene los siguientes parámetros:
    * start: inicio del intervalo. Por defecto, start = 0.
    * stop: final del intervalo.
    * step: tamaño del paso del intervalo. Por defecto, el tamaño del paso es 1.

In [16]:
arr2  = np.arange(start = 0, stop = 10) # 10 no se considera
print(arr2)

# o

arr2  = np.arange(0,10) 
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [17]:
# Agregando un tamaño de paso de 5 para crear un arreglo usando np.arrange
arr3  = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

**Usando np.linspace()**
* La función np.linspace() devuelve números que están distribuidos de manera uniforme con respecto al intervalo. En este caso, tanto el inicio como el final están incluidos.
* Tiene los siguientes parámetros:
    * start: inicio del intervalo. Por defecto, start = 0.
    * stop: final del intervalo.
    * num: número de muestras a generar. Por defecto, num = 50.

In [18]:
matrix2 = np.linspace(0,5) # Por defecto divide los datos en 50
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [19]:
#  Generando 10 valores equidistantes entre 10 y 20.
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**De manera similar, podemos crear matrices utilizando las funciones disponibles en la biblioteca NumPy.**

**Usando np.zeros()**

* La función np.zeros() se utiliza para crear una matriz y realizar operaciones de matriz en NumPy.
* Devuelve una matriz rellena con ceros del tamaño especificado.
* Tiene los siguientes parámetros:
  * shape: Número de filas y columnas en la matriz de salida.
  * dtype: tipo de datos de los elementos en la matriz, de forma predeterminada el valor se establece en float (flotante).

In [20]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Usando np.ones()**

* La función np.ones() es otra función para crear una matriz y realizar operaciones de matriz en NumPy.
* Devuelve una matriz del tamaño y tipo especificados, rellena con unos.
* Tiene los siguientes parámetros:
  * shape: Número de filas y columnas en la matriz de salida.
  * dtype: tipo de datos de los elementos en la matriz, de forma predeterminada el valor se establece en `float` (flotante).

In [21]:
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Usando np.eye()**
* La función np.eye() se utiliza para crear una matriz y realizar operaciones de matriz en NumPy.
* Devuelve una matriz con unos en la diagonal y ceros en las demás posiciones.
* Tiene los siguientes parámetros:
  * n: Número de filas y columnas en la matriz de salida.
  * dtype: tipo de datos de los elementos en la matriz, de forma predeterminada el valor se establece en `float` (flotante).

In [22]:
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**También podemos convertir un arreglo unidimensional en una matriz. Esto se puede hacer utilizando la función np.reshape()**

* La forma de un arreglo básicamente indica el número de elementos y las dimensiones del arreglo. Cambiar la forma de un arreglo de NumPy significa simplemente cambiar la forma del arreglo dado.
* Al cambiar la forma de un arreglo, podemos agregar o eliminar dimensiones o cambiar el número de elementos en cada dimensión.
* Para cambiar la forma de un arreglo de NumPy, utilizamos el método `reshape` con el arreglo dado.
* **Sintaxis:** array.reshape(shape)
  * shape: una tupla proporcionada como entrada, los valores en la tupla serán la nueva forma del arreglo.

In [23]:
# Definimos un arreglo del 0 al 9
arr4 = np.arange(0,10) 
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Cambiando la forma del arreglo arr4 a una matriz de 2 x 5.
arr4_reshaped = arr4.reshape((2,5))
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# y a una matriz de 2x6?
# arr4.reshape((2,6))

* Esto no funcionó porque tenemos 10 elementos que estamos intentando ajustar en una forma de 2 x 6, lo cual requeriría 12 elementos.

**NumPy también puede realizar una gran cantidad de operaciones matemáticas diferentes y proporciona diferentes funciones para hacerlo.**

NumPy proporciona:

1. Funciones trigonométricas.
2. Funciones exponenciales y logarítmicas.
3. Funciones para operaciones aritméticas entre arreglos y matrices.

**Trigonometric functions**

In [27]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495777


**Exponentes y Logaritmos**

In [28]:
np.exp(2)

7.38905609893065

In [29]:
arr5 = np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [30]:
# Por default toma el logaritmo base e
np.log(2)

0.6931471805599453

In [31]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [32]:
## Para logaritmo con base 10 usar log10
np.log10(8) 

0.9030899869919435

**Operaciones Aritméticas con Arreglos**

In [33]:
# Usando listas

l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)
# Está correcto?


[1, 2, 3, 4, 5, 6]


In [34]:
# Definimos 2 arreglos numpy

arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [35]:
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7**arr8) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


**Operaciones con Matrices**

In [36]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\Ernesto\AppData\Local\Temp\ipykernel_12960\2604038799.py:4: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


* RuntimeWarning: Los errores que ocurren durante la ejecución del programa (tiempo de ejecución) después de una compilación exitosa se llaman errores de tiempo de ejecución.
* Uno de los errores de tiempo de ejecución más comunes es la división por cero, también conocida como error de división.
* Debido al error de división por cero, obtenemos valores "inf" (infinito) porque 1/0 no es una operación definida.

**Algebra Lineal: Multiplicación de matrices**

In [38]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# Realizando la multiplicación de matrices en álgebra lineal (algunos pueden haberlo escuchado como el producto punto).
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpuesta de una matriz**

In [39]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# Transpuesta de una matriz
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
# Otra forma de calcular la transpuesta
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Función para encontrar los valores mínimo y máximo.**

In [42]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print('Minimum value: ',np.min(matrix9))

Minimum value:  1


In [44]:
print('Maximum value: ',np.max(matrix9))

Maximum value:  9


**Función para generar números aleatorios**

**Uso de la función np.random.rand**

* La función `np.random.rand` devuelve un array NumPy aleatorio cuyos elementos se eligen al azar de la distribución uniforme en el intervalo [0, 1) (incluyendo 0 pero excluyendo 1).
* **Sintaxis** - `np.random.rand(d0, d1)`
  * `d0, d1` - Representan las dimensiones del array requerido, proporcionadas como enteros, donde `d1` es opcional.

In [45]:
# Generando números aleatorios en un array
rand_mat = np.random.rand(5)
print(rand_mat)

[0.15314403 0.31791698 0.51227576 0.23277469 0.55670911]


In [46]:
# * Generando números aleatorios en una matriz
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)

[[0.86186909 0.22858681 0.86835797 0.72683499 0.86571493]
 [0.1552034  0.38092764 0.32533019 0.5004106  0.8605954 ]
 [0.4102231  0.30730164 0.28625757 0.8869423  0.87580547]
 [0.45983699 0.71331195 0.00217086 0.53688766 0.98524001]
 [0.63333601 0.26481904 0.99506198 0.66135192 0.53074913]]


**Uso de la función np.random.randn**

* La función `np.random.randn` devuelve un array NumPy aleatorio cuyas muestras se seleccionan al azar de la distribución normal estándar (con media 0 y desviación estándar 1).

* **Sintaxis** - `np.random.randn(d0, d1)`
  * `d0, d1` - Representan las dimensiones de la salida, donde `d1` es opcional.

In [47]:
# Generando números aleatorios en un array
rand_mat2 = np.random.randn(5) 
print(rand_mat2)

[-0.76377038 -0.44239951 -1.08951882 -0.51527037 -0.66530594]


In [48]:
# Generando números aleatorios en una matriz
rand_mat2 = np.random.randn(5,5) 
print(rand_mat2)

[[-1.17582012  1.79510676 -1.24660656  0.76825143 -0.98106155]
 [ 0.69247655  1.63191984 -0.45217404 -0.12564154 -0.48420054]
 [-1.04980817 -0.46809229  0.10901215 -0.44768411  0.13272616]
 [-0.3202806  -1.67797264  0.32843783  1.46899947  1.67672065]
 [ 0.30818983 -1.08571292 -1.67211761  0.8165275   1.01120811]]


In [49]:
# Revisemos el promedio y std
print('Mean:',np.mean(rand_mat2))
print('Standard Deviation:',np.std(rand_mat2))

Mean: -0.017903857101101702
Standard Deviation: 1.0316310207993895


*  Observamos que la media es muy cercana a 0 y la desviación estándar es muy cercana a 1.

**Uso de la función np.random.randint**

* La función `np.random.randint` devuelve un array NumPy aleatorio cuyos elementos se eligen al azar desde el límite inferior (inclusive) hasta el límite superior (exclusivo).

* **Sintaxis** - `np.random.randint(low, high, size)`
  * `low` - Representa el límite inferior inclusivo de la distribución desde donde se pueden extraer las muestras.
  * `high` - Representa el límite superior exclusivo de la distribución desde donde se pueden extraer las muestras.
  * `size` - Representa la forma de la salida.

In [50]:

rand_mat3 = np.random.randint(1,5,10)
print(rand_mat3)

[3 3 1 2 3 1 3 3 2 4]


In [51]:

rand_mat3 = np.random.randint(1,10,[5,5])
print(rand_mat3)

[[4 1 5 1 6]
 [3 4 7 6 3]
 [1 6 5 5 3]
 [7 3 2 8 2]
 [1 6 1 4 2]]


### 2.3 Accediento a elementos de una matriz

In [52]:
# Generemos una matriz con 10 valores aleatorios
rand_arr = np.random.randn(10)
print(rand_arr)

[-1.87990908 -0.3258443  -0.97962143 -1.05761564  0.39730543  1.59953742
 -1.12288894 -1.71288525  1.74055154 -0.96202936]


* Accedemos a 1 elemento

In [53]:

print(rand_arr[6])

-1.1228889430667006


* Accedemos a múltiples elementos

In [54]:

print(rand_arr[4:9])

[ 0.39730543  1.59953742 -1.12288894 -1.71288525  1.74055154]


In [55]:
# Accedemos a posiciones no consecutivas
print('Index de los valores a acceder: ',np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index de los valores a acceder:  [3 6 9]
[-1.05761564 -1.12288894 -0.96202936]


**Accedemos usando operaciones lógicas**

In [56]:
print(rand_arr)

[-1.87990908 -0.3258443  -0.97962143 -1.05761564  0.39730543  1.59953742
 -1.12288894 -1.71288525  1.74055154 -0.96202936]


In [57]:
rand_arr>0

array([False, False, False, False,  True,  True, False, False,  True,
       False])

In [58]:
# Accedemos a todos los valores > 0
print('Valores mayores a 0: ',rand_arr[rand_arr>0])

# y a los < 0
print('Valores menores a 0: ',rand_arr[rand_arr<0])

Valores mayores a 0:  [0.39730543 1.59953742 1.74055154]
Valores menores a 0:  [-1.87990908 -0.3258443  -0.97962143 -1.05761564 -1.12288894 -1.71288525
 -0.96202936]


**Accessing the entries of a Matrix**

In [59]:
# Generemos una matriz con números aleatorios
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[ 1.98659635  1.78813554  0.04087429 -0.58319949 -1.01644516]
 [-0.84504293  1.0070403   0.67482207  1.1700702  -1.06113947]
 [ 0.12728503  0.53842096 -1.10577325 -0.30721029 -0.8053553 ]
 [ 0.71429124  0.60640819 -0.65751922 -0.54432523  1.19462595]
 [-0.4895056   0.56412377  0.41419721  0.12376167 -0.46527208]]


In [60]:
# Accedemos a la segunda fila de la matriz
rand_mat[1]

array([-0.84504293,  1.0070403 ,  0.67482207,  1.1700702 , -1.06113947])

In [61]:
# Accedemos al tercer elemento del vector
print(rand_mat[1][2])

#o también

print(rand_mat[1,2])

0.6748220721345156
0.6748220721345156


In [62]:
# Accedemos a las primeras 2 filas y las columnas 1 y 2
print(rand_mat[0:2,1:3])

[[1.78813554 0.04087429]
 [1.0070403  0.67482207]]


**Accediento matrices usando operaciones lógicas**

In [63]:
print(rand_mat)

[[ 1.98659635  1.78813554  0.04087429 -0.58319949 -1.01644516]
 [-0.84504293  1.0070403   0.67482207  1.1700702  -1.06113947]
 [ 0.12728503  0.53842096 -1.10577325 -0.30721029 -0.8053553 ]
 [ 0.71429124  0.60640819 -0.65751922 -0.54432523  1.19462595]
 [-0.4895056   0.56412377  0.41419721  0.12376167 -0.46527208]]


In [64]:
# Todos los valores >0
print('Valores mayores a 0: \n ',rand_mat[rand_mat>0])

print('--------------------')
# Todos los valores < 0
print('Valores menores a 0: \n',rand_mat[rand_mat<0])

Valores mayores a 0: 
  [1.98659635 1.78813554 0.04087429 1.0070403  0.67482207 1.1700702
 0.12728503 0.53842096 0.71429124 0.60640819 1.19462595 0.56412377
 0.41419721 0.12376167]
--------------------
Valores menores a 0: 
 [-0.58319949 -1.01644516 -0.84504293 -1.06113947 -1.10577325 -0.30721029
 -0.8053553  -0.65751922 -0.54432523 -0.4895056  -0.46527208]


In [65]:
rand_mat[rand_mat>0]

array([1.98659635, 1.78813554, 0.04087429, 1.0070403 , 0.67482207,
       1.1700702 , 0.12728503, 0.53842096, 0.71429124, 0.60640819,
       1.19462595, 0.56412377, 0.41419721, 0.12376167])

**Modificando elementos de un array**

In [66]:
print(rand_arr)

[-1.87990908 -0.3258443  -0.97962143 -1.05761564  0.39730543  1.59953742
 -1.12288894 -1.71288525  1.74055154 -0.96202936]


In [67]:
# Cambiemos algunos valores!
rand_arr[3:5] = 5
print(rand_arr)

[-1.87990908 -0.3258443  -0.97962143  5.          5.          1.59953742
 -1.12288894 -1.71288525  1.74055154 -0.96202936]


In [68]:
# Cambiamos los elementos de índice 0 a 2 y 3 respectivamente
rand_arr[0:2] = [2,3]
print(rand_arr)

[ 2.          3.         -0.97962143  5.          5.          1.59953742
 -1.12288894 -1.71288525  1.74055154 -0.96202936]


In [69]:
# Modificamos valores usando operaciones lógicas
rand_arr[rand_arr>0] = 65
rand_arr

array([65.        , 65.        , -0.97962143, 65.        , 65.        ,
       65.        , -1.12288894, -1.71288525, 65.        , -0.96202936])

**Modificamos elementos de una matriz**

In [70]:
print(rand_mat3)

[[4 1 5 1 6]
 [3 4 7 6 3]
 [1 6 5 5 3]
 [7 3 2 8 2]
 [1 6 1 4 2]]


In [71]:
print('Matriz antes de la modificación: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('Matriz luego de la modificación: \n',rand_mat3)

Matriz antes de la modificación: 
 [[4 1 5 1 6]
 [3 4 7 6 3]
 [1 6 5 5 3]
 [7 3 2 8 2]
 [1 6 1 4 2]]
Matriz luego de la modificación: 
 [[4 1 5 1 6]
 [3 4 7 0 0]
 [1 6 5 0 0]
 [7 3 2 8 2]
 [1 6 1 4 2]]


In [72]:
# Extrayendo las 2 primeras filas y 3 primeros columnas de la matriz
sub_mat = rand_mat3[0:2,0:3]
print(sub_mat)

[[4 1 5]
 [3 4 7]]


In [73]:
# Cambiamos todos los valores de sub_mat a 3
sub_mat[:] = 3
print(sub_mat)

[[3 3 3]
 [3 3 3]]


In [74]:
# ¿Qué pasó con la matriz original luego que modificamos sub_mat?
rand_mat3

array([[3, 3, 3, 1, 6],
       [3, 3, 3, 0, 0],
       [1, 6, 5, 0, 0],
       [7, 3, 2, 8, 2],
       [1, 6, 1, 4, 2]])

In [75]:
#Para prevenir este comportamiento, debemos usar el método `.copy()` al asignar `sub_mat`.
rand_mat = np.random.randn(5,5)
print(rand_mat)
print('----------------------')
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat[:] = 3
print(sub_mat)
print('----------------------')
print(rand_mat)

[[-0.02029742  2.37061309 -1.35766056  0.38907797  1.03177374]
 [ 0.39223399 -0.4356676   0.54101601 -2.79656868  0.42015158]
 [-0.664329    0.49315142 -0.69875025 -1.33504682  1.83933608]
 [-1.11102434  0.51004024  0.31801407 -0.12350775 -0.79307851]
 [ 0.45658298  1.52372861  1.54802715 -0.61333745 -1.1338948 ]]
----------------------
[[3. 3. 3.]
 [3. 3. 3.]]
----------------------
[[-0.02029742  2.37061309 -1.35766056  0.38907797  1.03177374]
 [ 0.39223399 -0.4356676   0.54101601 -2.79656868  0.42015158]
 [-0.664329    0.49315142 -0.69875025 -1.33504682  1.83933608]
 [-1.11102434  0.51004024  0.31801407 -0.12350775 -0.79307851]
 [ 0.45658298  1.52372861  1.54802715 -0.61333745 -1.1338948 ]]


* Referencias
    * Practical Machine Learning Class  
    * https://nbviewer.org/github/albahnsen/PracticalMachineLearningClass/blob/master/notebooks/02-IntroPython_Numpy_Scypy_Pandas.ipynb

    * Data Science and Machine Learning: Making Data-Driven Decisions| MIT IDSS

    * Numpy: Official Documentation
    * https://numpy.org/